=== Nckcol/ruby-xml-parser/res/Plane.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="PlaneNS"
        xmlns="PlaneNS"
        elementFormDefault="qualified">

    <!--
    Model – название модели.
    Origin – страна производства.
    Chars (должно быть несколько) – характеристики, могут быть следующими: тип (самолет поддержки, сопровождения, истребитель, перехватчик, разведчик), кол-во мест (1 либо 2), боекомплект (есть либо нет [разведчик], если есть, то: ракеты [0 – 10]), наличие радара.
    Parameters – длина (в метрах), ширина (в метрах), высота (в метрах).
    Price – цена (в талерах).
    -->

    <xs:element name="Plane">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="planes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="planeItem" type="planeItem" minOccurs="1" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="model">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="origin">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="price">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="size">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="самолет поддержки"/>
            <xs:enumeration value="сопровождения"/>
            <xs:enumeration value="истребитель"/>
            <xs:enumeration value="перехватчик"/>
            <xs:enumeration value="разведчик"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="places">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="2"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="rockets">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="10"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="ammunition">
        <xs:sequence>
            <xs:element name="rockets" type="rockets"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="radar">
        <xs:restriction base="xs:boolean"/>
    </xs:simpleType>

    <xs:complexType name="planeItem">
        <xs:sequence>
            <xs:element name="id" type="xs:int"/>
            <xs:element name="model" type="model"/>
            <xs:element name="origin" type="origin"/>
            <xs:element name="price" type="price"/>
            <xs:element name="chars">
                <xs:complexType >
                    <xs:sequence>
                        <xs:element name="type" type="type"/>
                        <xs:element name="places" type="places" />
                        <xs:element name="radar" type="radar" />
                        <xs:element name="ammunition" type="ammunition"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="parameters">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="h" type="size" />
                        <xs:element name="l" type="size" />
                        <xs:element name="w" type="size" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Nckcol/ruby-xml-parser/res/PlaneList.xml
<?xml version="1.0" encoding="utf-8"?>
<Plane xmlns="PlaneNS"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="PlaneNS Plane.xsd">
    <planes>
        <planeItem>
            <id>0</id>
            <model>Some Model</model>
            <origin>Ukraine</origin>
            <price>1999</price>
            <chars>
                <humType>
                    <places>1</places>
                    <radar>false</radar>
                </humType>
            </chars>
            <parameters>
                <h>100</h>
                <l>20</l>
                <w>10</w>
            </parameters>
        </planeItem>
        <planeItem>
            <id>1</id>
            <model>Another Model</model>
            <origin>America</origin>
            <price>100</price>
            <chars>
                <militaryType>
                    <places>2</places>
                    <radar>true</radar>
                    <ammunition>
                        <rockets>5</rockets>
                    </ammunition>
                </militaryType>
            </chars>
            <parameters>
                <h>5</h>
                <l>5</l>
                <w>5</w>
            </parameters>
        </planeItem>
    </planes>
</Plane>
